### ISSUE TITLE
Github authentication

### ISSUE THREAD

**Issue by ameeetgaikwad** [asteroidai/asteroid#24]
Adding github authentication to the platform. 
If no one else is already working on this, would like to work on this!

@mlcocdav

**Comment by mlcocdav** [comment]
Hi @ameeetgaikwad, appreciate your interest in helping to build Asteroid! We're not supporting this repository anymore, the functionality moved to the core platform at http://asteroid.ai/. Let me know if you'd be interested in testing Asteroid when building AI agents!

**Comment by ameeetgaikwad** [comment]
hey @mlcocdav yes would love to. Also would love to contribute to the project, is this not OSS anymore?

**Comment by mlcocdav** [comment]
That's amazing, thank you so much @ameeetgaikwad! The OSS part moved to the [SDK](https://github.com/asteroidai/asteroid-python-sdk).

For example, you can contribute by creating more [custom supervisors](https://github.com/asteroidai/asteroid-python-sdk/blob/main/src/asteroid_sdk/supervision/custom_supervisors.py) and creating examples of using them in the [cookbook](https://github.com/asteroidai/cookbook)! You can sign up for [platform.asteroid.ai](platform.asteroid.ai) and start building the supervisors.

**Comment by ameeetgaikwad** [comment]
> That's amazing, thank you so much @ameeetgaikwad! The OSS part moved to the [SDK](https://github.com/asteroidai/asteroid-python-sdk).
> 
> For example, you can contribute by creating more [custom supervisors](https://github.com/asteroidai/asteroid-python-sdk/blob/main/src/asteroid_sdk/supervision/custom_supervisors.py) and creating examples of using them in the [cookbook](https://github.com/asteroidai/cookbook)! You can sign up for [platform.asteroid.ai](platform.asteroid.ai) and start building the supervisors.

thanks man! LFG
